import { PanelOperativoImagen } from './index';
import { NgxGalleryOptions, NgxGalleryImage } from 'ngx-gallery';

export interface PanelOperativo {
    iD: number;
    incidenteId: number;
    gradoColor: string;
    grado: string;
    cliente: string;
    // nroIncidente: number;
    flgReclamo: number;
    reclamo: string;
    flgAviso: number;
    domicilio: string;
    sintomas: string;
    zonaColor: string;
    localidadDescripcion: string;
    localidad: string;
    sexoEdad: string;
    movil: string;
    flgMovilPreasignado: number;
    flgEnviado: number;
    errorEnvio: string;
    horLlamada: Date | string | null;
    fecLlamada: Date | string | null;
    Paciente: string;
    dmReferencia: string;
    movilPreasignado: number | null;
    sanatorio: string;
    viajeId: string;
    tpoDespacho: number;
    tpoSalida: number | null;
    tpoDesplazamiento: number | null;
    tpoAtencion: number | null;
    tpoLlegada: number;
    aviso: string;
    dmLatitud: number | null;
    dmLongitud: number | null;
    gradoOperativoId: number;
    zonaGeograficaId: number;
    grupoOperativoId: number;
    ultimoSuceso: string;
    clrDespacho: string;
    clrSalida: string;
    clrDesplazamiento: string;
    clrAtencion: string;
    clrLlegada: string;
    virTpoDerivacion: string;
    virTpoInternacion: string;
    clrDerivacion: string;
    clrInternacion: string;
    domicilioDestino: string;
    localidadDestino: string;
    zonaDestinoColor: string;
    franjaHoraria: number;
    clasificacionId: number;
    colorCliente: string;
    flgSimultaneo: number;
    incidenteLogRefreshId: number;
    dmEntreCalle1: string;
    dmEntreCalle2: string;

    panelOperativoImagenes: PanelOperativoImagen[];
    galleryOptions: NgxGalleryOptions[];
    galleryImages: NgxGalleryImage[];
}
